### ISSUE TITLE
Support generating changelogs

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/Vib#5]
Image-based operating systems, which are the target of Vib, are [often not just packages](https://github.com/Vanilla-OS/ABRoot/issues/115), and if they use Vib it's very likely they're using meson, go, cmake, make, shell scripts, or whatever to deliver software and customizations.

The idea is to allow image maintainers to add comments in the recipe, so as to automatically generate the changelog with the build, and use a prefix to define the version.

Here is an example:

```yaml
modules:
- name: init-setup
  type: shell
  commands:
  # v0.1: the PATH environment now supports listing binaries from /usr/local/bin
  - echo 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"' > /etc/environment
  - sed -i '4,10d' /etc/profile
  - apt update
  - apt upgrade -y
  - apt clean
  # v0.2: prevented snap from being installed as a dependency
  - apt-mark hold snapd gnome-software-plugin-snap

# v0.1: implemented the Vanilla Tools
- name: vanilla-tools
  type: shell
  source:
    type: tar
    # switch to production build once in production
    url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/continuous/vanilla-tools.tar.gz
  commands:
  - mkdir -p /usr/bin
  - cp /sources/vanilla-tools/lpkg /usr/bin/lpkg
  - cp /sources/vanilla-tools/cur-gpu /usr/bin/cur-gpu
  - chmod +x /usr/bin/lpkg
  - chmod +x /usr/bin/cur-gpu
```

Vib should be smart enough to generate a changelog for the greeter version which is `v0.2` in this case. It could also generate an extended version with all the comments grouped by version.

**Comment by pietrodicaprio** [comment]
I do not agree with the proposal. It would be messy and difficult to read.\
The Contribution Guidelines that we published are already meant to simplify the changelog management as the list of commits from tag A to tag B are already listing the tasks, thus the changes, between two releases. The output of this diff can be automatied.

Each component/package must have its changelog. A component that includes a subset of components will have a simple reference to the component version update in the changelog., for example `#000 update ABRoot to x.y.z`.

We have to make difference between Changelog and Release Notes (a good read here: https://amoeboids.com/blog/changelog-vs-release-notes-the-key-differences/ ).\
The Release Notes to the user would not simply state `#000 update ABRoot to x.y.z` but, along with it, would list the _meaningful_ changes between the version that was previously used and the one that has been targeted.

Automating the first part of this method requires some development that I'll handle. For the Alpha release I'll prepare the documents manually.

**Comment by mirkobrombin** [comment]
The issue is still to be discussed, it deserves a meeting to evaluate all aspects before deciding.
